version: "3.9"

services:
backend:
  build:
    context: . # ðŸ‘ˆ project root, not ./backend
    dockerfile: backend/Dockerfile
  image: dineshrajannds/backend:v3.5
  restart: always
  ports:
    - "8123:8000" # ðŸ‘ˆ external 8123 â†’ internal 8000
  environment:
    - ENV=${ENV}
    - MONGO_URI=${MONGO_URI}
  depends_on:
    - db
  healthcheck:
    test: [ "CMD-SHELL", "curl -f http://localhost:8000/api/projects/ || exit 1" ]
    interval: 30s
    timeout: 10s
    retries: 5
    start_period: 40s

  api:
    image: dineshrajannds/api:v3.3
    restart: always
    ports:
      - "8001:8001"
    environment:
      - ENV=${ENV}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - db
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8001/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    image: dineshrajannds/frontend:v3.3
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_EXTRA_API=http://api:8001
    depends_on:
      - backend
      - api

  db:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongosh", "--username", "${MONGO_INITDB_ROOT_USERNAME}", "--password", "${MONGO_INITDB_ROOT_PASSWORD}", "--authenticationDatabase=admin", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:

    # Build & push examples
    # docker build -t dineshrajannds/api:v8. -f api/Dockerfile ./api
    # docker build -t dineshrajannds/backend:v9 . -f backend/Dockerfile
    # docker build -t dineshrajannds/frontend:v9. -f frontend/Dockerfile ./frontend

    # docker login
    # docker push dineshrajannds/backend:v9
    # docker push dineshrajannds/api:v9
    # docker push dineshrajannds/frontend:v9

    # python manage.py runserver
